#!/bin/bash

PYTHON_BIN=.venv/bin/python \
BASE_OUT=phase_aware_v1 \
CYCLES=30 \
OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 NUMEXPR_NUM_THREADS=1 \
PARALLEL_JOBS=3 \
CKPT_A=phase_aware_v1/cycle_4/branch_A/checkpoints/policy_u10.pt \
CKPT_B=phase_aware_v1/cycle_2/branch_A/checkpoints/policy_u20.pt \
CKPT_C=phase_aware_v1/cycle_3/branch_C/checkpoints/policy_u30.pt \
TOTAL_UPDATES=20 \
REPORT_EVERY=10 \
ROLLOUT_STEPS=768 \
GAMES_PER_SEAT=20 \
MAX_EPISODE_STEPS=500 \
EVAL_MAX_STEPS=2500 \
MODEL_ARCH=graph_entity_phase_aware_hybrid \
MODEL_HIDDEN=192 \
MODEL_RESIDUAL_BLOCKS=3 \
PPO_LR=0.00005 \
PPO_ENT_COEF=0.02 \
PPO_EPOCHS=1 \
THREAT_DEV_CARD_WEIGHT=0.7 \
OPPONENT_SEAT_COUNT=2 \
MIX_RANDOM=0.10 \
MIX_FROZEN=0.55 \
REWARD_SHAPING_MAIN_ROAD_PURPOSE=0.05 \
REWARD_SHAPING_SETUP_SETTLEMENT=0.40 \
SETUP_SELECTION_INFLUENCE_SETTLEMENT_PROB=0.90 \
SETUP_SELECTION_INFLUENCE_SETTLEMENT_ROUND2_PROB=1.00 \
SETUP_SELECTION_INFLUENCE_PROB=0.00 \
SETUP_SELECTION_INFLUENCE_ROAD_PROB=0.05 \
REWARD_SHAPING_SETUP_ROAD_FRONTIER=0.03 \
REWARD_SHAPING_SETUP_ROUND1_FLOOR=0.20 \
REWARD_SHAPING_OWS_ACTIONS=0.02 \
TRADE_MODE=guided \
MAX_TRADE_PROPOSALS=1 \
REWARD_SHAPING_TRADE_OFFER_VALUE=0.00 \
REWARD_SHAPING_TRADE_ACCEPT_VALUE=0.00 \
REWARD_SHAPING_BANK_TRADE_VALUE=0.00 \
REWARD_SHAPING_TRADE_REJECT_BAD_OFFER_VALUE=0.00 \
REWARD_SHAPING_ROB_LEADER=0.02 \
REWARD_SHAPING_VP=0.0 \
REWARD_SHAPING_RESOURCE=0.0 \
REWARD_SHAPING_TERMINAL_TABLE_MEAN=0.04 \
REWARD_SHAPING_PLAY_KNIGHT=0.00 \
REWARD_SHAPING_PLAY_KNIGHT_WHEN_BLOCKED=0.02 \
REWARD_SHAPING_KNIGHT_UNBLOCK_PENALTY=0.003 \
FORCE_KNIGHT_BOOTSTRAP_PROB=0.00 \
FORCE_KNIGHT_BOOTSTRAP_UPDATES=0 \
RESET_WEAKEST_FROM_CHAMP=1 \
RESET_SOURCE_CHAMP_PROB=0.65 \
RESET_SOURCE_ANCHOR_PROB=0.35 \
ANCHOR_MANIFEST= \
ANCHOR_TAG_FILTER= \
GUARANTEE_ANCHOR_EXPOSURE=1 \
ANCHOR_MIN_FROZEN_PROB=0.45 \
PROMOTION_GATE_ENABLE=1 \
PROMOTION_MIN_STRICT=0.43 \
PROMOTION_MIN_WORST_SEAT=0.28 \
PROMOTION_MIN_OPENING=0.33 \
PROMOTION_BORDERLINE_MARGIN=0.02 \
PROMOTION_BORDERLINE_GAMES_PER_SEAT=24 \
bash league3.sh

##REWARD_SHAPING_MAIN_ROAD_PURPOSE=0.08 \
##REWARD_SHAPING_SETUP_SETTLEMENT=0.21 \
##SETUP_SELECTION_INFLUENCE_SETTLEMENT_PROB=0.38 \

#OPPONENT_SEAT_COUNT=2 \
#MIX_FROZEN=0.7 \

#REWARD_SHAPING_TERMINAL_TABLE_MEAN=0.10 \
#REWARD_SHAPING_PLAY_KNIGHT=0.15 \
#REWARD_SHAPING_PLAY_KNIGHT_WHEN_BLOCKED=0.30 \
#REWARD_SHAPING_KNIGHT_UNBLOCK_PENALTY=0.08 \
#FORCE_KNIGHT_BOOTSTRAP_PROB=0.12 \
#FORCE_KNIGHT_BOOTSTRAP_UPDATES=12 \
#REWARD_SHAPING_PLAY_KNIGHT_WHEN_BLOCKED=0.004
#REWARD_SHAPING_KNIGHT_UNBLOCK_PENALTY=0.003

#OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 NUMEXPR_NUM_THREADS=1 \
#PARALLEL_JOBS=3 \
#THREAT_DEV_CARD_WEIGHT=0.7 \
#REWARD_SHAPING_ROB_LEADER=0.005 \
#REWARD_SHAPING_SETUP_SETTLEMENT=0.06 \
#REWARD_SHAPING_TERMINAL_TABLE_MEAN=0.10 \
#CYCLE=15 \
#bash league3.sh

#REWARD_SHAPING_ROBBER_BLOCK_LEADER=0.02 \
#REWARD_SHAPING_ROB_LEADER=0.015 \
#REWARD_SHAPING_ROB_MISTARGET=0.005 \
#REWARD_SHAPING_PLAY_KNIGHT=0.06 \
#CKPT_A=league_runs_hybrid_v1/cycle_92/branch_A/best_checkpoint.pt \
#CKPT_B=league_runs_hybrid_v1/cycle_92/branch_B/best_checkpoint.pt \
#CKPT_C=league_runs_hybrid_v1/cycle_92/branch_C/best_checkpoint.pt \
#MODEL_ARCH=graph_entity_hybrid \
#OPPONENT_SEAT_COUNT=3 \
#MIX_RANDOM=0.0 \
#MIX_FROZEN=1.0 \
#CKPT_A=bpg_s4102/checkpoints/policy_u30.pt \
#CKPT_B=bpg_s4102/checkpoints/policy_u30.pt \
#CKPT_C=bpg_s4102/checkpoints/policy_u30.pt \
#OPPONENT_SEAT_COUNT=2 \
#MIX_RANDOM=0.1 \
#MIX_FROZEN=0.5 \
