#!/bin/bash
OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 NUMEXPR_NUM_THREADS=1 \
PARALLEL_JOBS=3 \
THREAT_DEV_CARD_WEIGHT=0.7 \
REWARD_SHAPING_ROB_LEADER=0.005 \
REWARD_SHAPING_SETUP_SETTLEMENT=0.06 \
REWARD_SHAPING_TERMINAL_TABLE_MEAN=0.10 \
CYCLE=15 \
bash league3.sh

#REWARD_SHAPING_ROBBER_BLOCK_LEADER=0.02 \
#REWARD_SHAPING_ROB_LEADER=0.015 \
#REWARD_SHAPING_ROB_MISTARGET=0.005 \
#REWARD_SHAPING_PLAY_KNIGHT=0.06 \
